version: '3.8'

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn kontorshund.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/home/kontorshund/web/staticfiles
      - media_volume:/home/kontorshund/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    build: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/kontorshund/web/staticfiles
      - media_volume:/home/kontorshund/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: