version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn kontorshund.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/home/kontorshund/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/kontorshund/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: