version: '3.8'

services:
  web:
    #image: index.docker.io/oneandonly1337/kontorshund:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/kontorshund/web
      - static_volume:/home/kontorshund/web/staticfiles
      - ./mediafiles:/home/kontorshund/web/mediafiles
      #- media_volume:/home/kontorshund/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: "supercronic /crontab"
    volumes:
      - ./crontab:/crontab:ro
    env_file:
      - ./.env.dev

volumes:
  static_volume:
  media_volume:
