version: '3.8'

services:
  web:
    #mage: index.docker.io/oneandonly1337/kontorshund
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/kontorshund/web/staticfiles
      - media_volume:/home/kontorshund/web/mediafiles
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env.dev

volumes:
  static_volume:
  media_volume: