version: '3.8'

services:

  test-db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    #image: index.docker.io/oneandonly1337/kontorshund:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/dockeruser/web
      - static_volume:/home/dockeruser/web/staticfiles
      - ./mediafiles:/home/dockeruser/web/mediafiles
      #- media_volume:/home/dockeruser/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./dev.env
    depends_on:
      - test-db

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: /bin/sh -c "/home/dockeruser/web/cron_startup.sh" 
  #   volumes:
  #    # - .:/home/kontorshund/web
  #     - ./crontab:/crontab:ro
  #   env_file:
  #     - ./dev.env

volumes:
  static_volume:
  media_volume:
