version: '3.8'

services:

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: /bin/sh -c "/home/dockeruser/web/cron_startup.sh" 
    volumes:
      # - .:/home/kontorshund/web
      - ./crontab:/crontab:ro
    env_file:
      - ./.env.prod