version: '3.8'


services:

  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes: 
    - .:/code
    ports: 
      - 8000:8000

  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

