version: '3.8'

services:

  web:
    container_name: web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    image: index.docker.io/oneandonly1337/kontorshund
    #build:
    #  context: .
    #  dockerfile: Dockerfile.prod
    command: gunicorn kontorshund.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/home/kontorshund/web/staticfiles
      - media_volume:/home/kontorshund/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  
  nginx-proxy:
    container_name: nginx-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    build: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/kontorshund/web/staticfiles
      - media_volume:/home/kontorshund/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower 
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env.prod
    command: --interval 30 --label-enable

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: