# Generated by Django 3.2.9 on 2022-02-20 11:27

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_municipality_province'), ('core', '0003_auto_20211128_2006'), ('core', '0004_advertisement_area'), ('core', '0005_alter_advertisement_area'), ('core', '0006_alter_advertisement_province'), ('core', '0007_auto_20211130_1928'), ('core', '0008_advertisement_is_offering_own_dog'), ('core', '0009_alter_advertisement_breed'), ('core', '0010_auto_20211201_1851'), ('core', '0011_auto_20211204_1324'), ('core', '0012_auto_20211204_1351'), ('core', '0013_alter_advertisement_breed'), ('core', '0014_alter_advertisement_breed'), ('core', '0015_payments'), ('core', '0016_advertisement_is_published'), ('core', '0017_alter_advertisement_is_published'), ('core', '0018_advertisement_payment_type'), ('core', '0019_alter_advertisement_payment_type'), ('core', '0020_auto_20211226_1122'), ('core', '0021_rename_payments_payment'), ('core', '0022_alter_payment_payment_reference'), ('core', '0023_alter_payment_payer_alias'), ('core', '0024_auto_20211229_2011'), ('core', '0025_auto_20211229_2034'), ('core', '0026_rename_breed_advertisement_hundras'), ('core', '0027_area_province'), ('core', '0028_alter_advertisement_author'), ('core', '0029_alter_advertisement_is_offering_own_dog'), ('core', '0030_alter_advertisement_area'), ('core', '0031_alter_advertisement_description'), ('core', '0032_auto_20220104_2024'), ('core', '0033_auto_20220106_1358'), ('core', '0034_auto_20220106_1530'), ('core', '0035_auto_20220106_1540'), ('core', '0036_newsmails'), ('core', '0037_auto_20220107_2159'), ('core', '0038_auto_20220107_2213'), ('core', '0039_auto_20220107_2215'), ('core', '0040_auto_20220108_1231'), ('core', '0041_auto_20220108_1528'), ('core', '0042_newsemail_uuid'), ('core', '0043_alter_newsemail_user'), ('core', '0044_advertisement_ad_views'), ('core', '0045_advertisement_deletion_data'), ('core', '0046_rename_deletion_data_advertisement_deletion_date'), ('core', '0047_advertisement_is_deleted'), ('core', '0048_alter_newsemail_uuid'), ('core', '0049_alter_newsemail_province'), ('core', '0050_alter_advertisement_province'), ('core', '0051_province_count'), ('core', '0052_auto_20220115_1359'), ('core', '0053_auto_20220119_1642'), ('core', '0054_auto_20220217_2039'), ('core', '0055_auto_20220220_1118'), ('core', '0056_remove_advertisement_is_offering_own_dog')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('offering_count', models.IntegerField(default=0)),
                ('requesting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.province')),
                ('offering_count', models.IntegerField(default=0)),
                ('requesting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
                ('offering_count', models.IntegerField(default=0)),
                ('requesting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DogSizeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150, verbose_name='Annons-Titel')),
                ('description', models.TextField(max_length=1500, verbose_name='Annons-beskrivning')),
                ('days_per_week', models.CharField(choices=[('1', '1 dag per vecka'), ('1-2', '1-2 dagar per vecka'), ('1-3', '1-3 dagar per vecka'), ('1-4', '1-4 dagar per vecka'), ('1-5', '1-5 dagar per vecka')], default=1, max_length=3, verbose_name='Önskad omfattning')),
                ('hundras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dogbreeds', verbose_name='Hundras')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality', verbose_name='Kommun')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap/Storstad')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='Område')),
                ('image1', stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 1')),
                ('image2', stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 2')),
                ('image3', stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 3')),
                ('size_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_offered', to='core.dogsizechoices', verbose_name='Hundens storlek')),
                ('size_requested', models.ManyToManyField(related_name='size_requested', to='core.DogSizeChoices', verbose_name='Önskade hundstorlekar (flerval)')),
                ('is_published', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('S', 'Swish'), ('B', 'Bankgiro')], default=1, max_length=1, verbose_name='Betalningsmetod')),
                ('age', models.IntegerField(default=0, verbose_name='Hundens ålder (år)')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Hundens namn')),
                ('ad_views', models.IntegerField(default=0)),
                ('deletion_date', models.DateField(default=core.models.get_30_days_ahead)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ad_kind', models.CharField(choices=[('OF', 'Offering'), ('RQ', 'Requesting')], default='OF', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('1', 'Initial payment'), ('2', 'Extend payment'), ('3', 'Other')], default=1, max_length=1, verbose_name='payment_type')),
                ('amount', models.IntegerField()),
                ('payment_reference', models.CharField(max_length=50)),
                ('date_time_paid', models.DateTimeField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertisement', verbose_name='advertisement')),
                ('payer_alias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(blank=True, choices=[(1, 'Veckovis'), (2, 'Dagligen')], null=True, verbose_name='Intervall')),
                ('areas', models.ManyToManyField(blank=True, to='core.Area', verbose_name='Område')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipality', verbose_name='Kommun')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap/Storstad')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ad_type', models.IntegerField(blank=True, choices=[(1, 'Erbjudes'), (2, 'Sökes')], null=True, verbose_name='Annonstyp')),
                ('is_active', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
