# Generated by Django 3.2.9 on 2022-02-20 15:37

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Senast ändrad')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ad_kind', models.CharField(choices=[('OF', 'Offering'), ('RQ', 'Requesting')], default='OF', max_length=4, verbose_name='Annonstyp')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicerad')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Borttagen')),
                ('deletion_date', models.DateField(default=core.models.get_one_month_ahead_from_today, verbose_name='Borttagnings-datum')),
                ('ad_views', models.IntegerField(default=0, verbose_name='Visningar')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Hundens namn')),
                ('age', models.IntegerField(default=0, verbose_name='Hundens ålder (år)')),
                ('title', models.CharField(max_length=150, verbose_name='Annons-Titel')),
                ('description', models.TextField(max_length=1500, verbose_name='Annons-beskrivning')),
                ('days_per_week', models.CharField(choices=[('1', '1 dag per vecka'), ('1-2', '1-2 dagar per vecka'), ('1-3', '1-3 dagar per vecka'), ('1-4', '1-4 dagar per vecka'), ('1-5', '1-5 dagar per vecka')], default=1, max_length=3, verbose_name='Önskad omfattning')),
                ('payment_choice', models.CharField(choices=[('S', 'Swish'), ('B', 'Bankgiro')], default=1, max_length=1, verbose_name='Betalningsmetod')),
                ('image1', stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 1')),
                ('image2', stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 2')),
                ('image3', stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offering_count', models.IntegerField(default=0)),
                ('requesting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DogSizeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offering_count', models.IntegerField(default=0)),
                ('requesting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('offering_count', models.IntegerField(default=0)),
                ('requesting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_kind', models.CharField(choices=[('IN', 'Initial'), ('EX', 'Extended')], default='IN', max_length=2, verbose_name='Betalningstyp')),
                ('amount', models.IntegerField()),
                ('payment_reference', models.CharField(max_length=50)),
                ('date_time_paid', models.DateTimeField()),
                ('payer_alias', models.CharField(max_length=50)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertisement', verbose_name='advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='NewsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(blank=True, choices=[(1, 'Veckovis'), (2, 'Dagligen')], null=True, verbose_name='Intervall')),
                ('ad_type', models.IntegerField(blank=True, choices=[(1, 'Erbjudes'), (2, 'Sökes')], null=True, verbose_name='Annonstyp')),
                ('is_active', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('areas', models.ManyToManyField(blank=True, to='core.Area', verbose_name='Område')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipality', verbose_name='Kommun')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap/Storstad')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
        migrations.AddField(
            model_name='area',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
        migrations.AddField(
            model_name='area',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='Område'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Författare'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='hundras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dogbreed', verbose_name='Hundras'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality', verbose_name='Kommun'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap/Storstad'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='size_offered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_offered', to='core.dogsizechoice', verbose_name='Hundens storlek'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='size_requested',
            field=models.ManyToManyField(related_name='size_requested', to='core.DogSizeChoice', verbose_name='Önskade hundstorlekar (flerval)'),
        ),
    ]
