# Generated by Django 3.2.9 on 2022-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_kind',
            field=models.CharField(choices=[('OF', 'Offering'), ('RQ', 'Requesting')], default='OF', max_length=2, verbose_name='Annonstyp'),
        ),
    ]
