# Generated by Django 3.2.9 on 2022-03-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_advertisement_ad_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='ad_type',
            field=models.CharField(choices=[('Erbjudes', 'Offering'), ('Sökes', 'Requesting')], default='Erbjudes', max_length=10, verbose_name='Annonstyp'),
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='interval',
            field=models.CharField(choices=[('Veckovis', 'Weekly'), ('Dagligen', 'Daily')], default='Veckovis', max_length=10, verbose_name='Intervall'),
        ),
    ]
