# Generated by Django 3.2.9 on 2022-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220301_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='interval',
            field=models.CharField(choices=[('Veckovis', 'Veckovis'), ('Dagligen', 'Daglingen')], default='Veckovis', max_length=10, verbose_name='Intervall'),
        ),
    ]
