# Generated by Django 3.2.9 on 2021-11-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advertisement_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
    ]
