# Generated by Django 3.2.9 on 2022-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newsemail_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='interval',
            field=models.CharField(choices=[('Veckovis', 'Veckovis'), ('asdasd', 'dfgdfg')], default='Veckovis', max_length=10, verbose_name='Intervall'),
        ),
    ]
