# Generated by Django 3.2.9 on 2021-11-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_advertisement_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap'),
        ),
    ]
