# Generated by Django 3.2.9 on 2022-03-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220301_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='interval',
            field=models.CharField(choices=[('aaaa', 'bbbb'), ('cccc', 'dddd')], max_length=10, verbose_name='Intervall'),
        ),
    ]
