# Generated by Django 3.2.9 on 2022-03-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_newsemail_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='ad_type',
            field=models.CharField(choices=[('OF', 'Erbjudes'), ('RQ', 'Sökes')], default='OF', max_length=2, verbose_name='Annonstyp'),
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='interval',
            field=models.CharField(choices=[('WK', 'Veckovis'), ('DL', 'Dagligen')], default='WK', max_length=2, verbose_name='Intervall'),
        ),
    ]
