# Generated by Django 3.2.9 on 2021-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211130_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_offering_own_dog',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
