# Generated by Django 3.2.9 on 2022-03-03 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20220301_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsemail', to=settings.AUTH_USER_MODEL),
        ),
    ]
