# Generated by Django 3.2.9 on 2021-12-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211201_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogSizeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='size',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='days_per_week',
            field=models.CharField(choices=[('1', '1 dag per vecka'), ('1-5', '1-2 dagar per vecka'), ('1-3', '1-3 dagar per vecka'), ('1-4', '1-4 dagar per vecka'), ('1-5', '1-5 dagar per vecka')], default=1, max_length=3, verbose_name='Omfattning'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='size_offered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_offered', to='core.dogsizechoices', verbose_name='Min hunds storlek'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='size_requested',
            field=models.ManyToManyField(null=True, related_name='size_requested', to='core.DogSizeChoices', verbose_name='Möjliga hundstorlekar'),
        ),
    ]
