# Generated by Django 3.2.9 on 2021-12-16 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_advertisement_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('1', 'Initial payment'), ('2', 'Extend ad run-time payment'), ('3', 'Other')], default=1, max_length=1, verbose_name='payment_type')),
                ('amount', models.IntegerField()),
                ('payment_reference', models.CharField(max_length=25)),
                ('date_time', models.DateTimeField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertisement', verbose_name='advertisement')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
