# Generated by Django 3.2.9 on 2021-12-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
