# Generated by Django 3.2.9 on 2021-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_advertisement_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
