# Generated by Django 3.2.9 on 2021-12-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_advertisement_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='date_time',
            new_name='date_time_paid',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payer',
        ),
        migrations.AddField(
            model_name='payments',
            name='payer_alias',
            field=models.IntegerField(null=True),
        ),
    ]
