# Generated by Django 3.2.9 on 2021-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_payments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(max_length=50),
        ),
    ]
