# Generated by Django 3.2.9 on 2021-12-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_payment_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer_alias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
