# Generated by Django 3.2.9 on 2021-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_payment_payer_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Ålder'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Namn'),
        ),
    ]
