# Generated by Django 3.2.9 on 2021-12-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20211229_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Hundens ålder (år)'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Annons-beskrivning'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild 1'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild 2'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild 3'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Hundens namn'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Annons-Titel'),
        ),
    ]
