# Generated by Django 3.2.9 on 2021-12-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20211229_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='breed',
            new_name='hundras',
        ),
    ]
