# Generated by Django 3.2.9 on 2021-12-30 13:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_area_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='municipality',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
    ]
