# Generated by Django 3.2.9 on 2021-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_advertisement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='is_offering_own_dog',
            field=models.BooleanField(null=True),
        ),
    ]
