# Generated by Django 3.2.9 on 2021-12-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_advertisement_is_offering_own_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='Område'),
        ),
    ]
