# Generated by Django 3.2.9 on 2022-01-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_advertisement_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Annons-beskrivning'),
        ),
    ]
