# Generated by Django 3.2.9 on 2022-01-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_advertisement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Hundens namn'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='size_offered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_offered', to='core.dogsizechoices', verbose_name='Hundens storlek'),
        ),
    ]
