# Generated by Django 3.2.9 on 2022-01-06 13:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220104_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='days_per_week',
            field=models.CharField(choices=[('1', '1 dag per vecka'), ('1-5', '1-2 dagar per vecka'), ('1-3', '1-3 dagar per vecka'), ('1-4', '1-4 dagar per vecka'), ('1-5', '1-5 dagar per vecka')], default=1, max_length=3, verbose_name='Önskad omfattning'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 1'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Hundens namn'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='size_requested',
            field=models.ManyToManyField(related_name='size_requested', to='core.DogSizeChoices', verbose_name='Önskade hundstorlekar (flerval)'),
        ),
    ]
