# Generated by Django 3.2.9 on 2022-01-06 15:30

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220106_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 1'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 2'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.content_file_name, verbose_name='Bild 3'),
        ),
    ]
