# Generated by Django 3.2.9 on 2022-01-07 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_newsmails'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(choices=[(1, 'Veckovis'), (2, 'Dagligen')])),
                ('weekly', models.BooleanField(default=False, verbose_name='Veckovis')),
                ('daily', models.BooleanField(default=False, verbose_name='Dagligen')),
                ('areas', models.ManyToManyField(to='core.Area', verbose_name='Område')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality', verbose_name='Kommun')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='DogBreeds',
            new_name='DogBreed',
        ),
        migrations.RenameModel(
            old_name='DogSizeChoices',
            new_name='DogSizeChoice',
        ),
        migrations.DeleteModel(
            name='NewsMails',
        ),
    ]
