# Generated by Django 3.2.9 on 2022-01-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220107_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsemail',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='newsemail',
            name='weekly',
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='areas',
            field=models.ManyToManyField(null=True, to='core.Area', verbose_name='Område'),
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='interval',
            field=models.IntegerField(choices=[(1, 'Veckovis'), (2, 'Dagligen')], null=True),
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipality', verbose_name='Kommun'),
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap'),
        ),
    ]
