# Generated by Django 3.2.9 on 2022-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20220107_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsemail',
            name='ad_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Hund erbjudes'), (2, 'Hund sökes')], null=True, verbose_name='Annonstyp'),
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(1, 'Veckovis'), (2, 'Dagligen')], null=True, verbose_name='Intervall'),
        ),
    ]
