# Generated by Django 3.2.9 on 2022-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20220108_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsemail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsemail',
            name='ad_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Erbjudes'), (2, 'Sökes')], null=True, verbose_name='Annonstyp'),
        ),
    ]
