# Generated by Django 3.2.9 on 2022-01-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_advertisement_deletion_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='deletion_data',
            new_name='deletion_date',
        ),
    ]
