# Generated by Django 3.2.9 on 2022-01-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rename_deletion_data_advertisement_deletion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
