# Generated by Django 3.2.9 on 2022-01-13 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_advertisement_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
