# Generated by Django 3.2.9 on 2022-01-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_newsemail_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsemail',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Landskap/Storstad'),
        ),
    ]
