# Generated by Django 3.2.9 on 2022-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_advertisement_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
