# Generated by Django 3.2.9 on 2022-01-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20220115_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='count',
            new_name='offering_count',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='count',
            new_name='offering_count',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='count',
            new_name='offering_count',
        ),
        migrations.AddField(
            model_name='area',
            name='requesting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipality',
            name='requesting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='requesting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='days_per_week',
            field=models.CharField(choices=[('1', '1 dag per vecka'), ('1-2', '1-2 dagar per vecka'), ('1-3', '1-3 dagar per vecka'), ('1-4', '1-4 dagar per vecka'), ('1-5', '1-5 dagar per vecka')], default=1, max_length=3, verbose_name='Önskad omfattning'),
        ),
    ]
