# Generated by Django 3.2.9 on 2022-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20220217_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_kind',
            field=models.CharField(choices=[('OF', 'Offering'), ('RQ', 'Requesting')], default='OF', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Initial payment'), ('2', 'Extend payment'), ('3', 'Other')], default=1, max_length=1, verbose_name='payment_type'),
        ),
    ]
