# Generated by Django 3.2.9 on 2022-02-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20220220_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_offering_own_dog',
        ),
    ]
