# Generated by Django 3.2.9 on 2022-02-20 14:11

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_remove_advertisement_is_offering_own_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='payment_type',
            new_name='payment_choice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_kind',
            field=models.CharField(choices=[('IN', 'Initial'), ('EX', 'Extended')], default='IN', max_length=2, verbose_name='Betalningstyp'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_kind',
            field=models.CharField(choices=[('OF', 'Offering'), ('RQ', 'Requesting')], default='OF', max_length=2, verbose_name='Annonstyp'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_views',
            field=models.IntegerField(default=0, verbose_name='Visningar'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Författare'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Skapad'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='deletion_date',
            field=models.DateField(default=core.models.get_30_days_ahead, verbose_name='Borttagnings-datum'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Borttagen'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicerad'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Senast ändrad'),
        ),
    ]
