
breeds = [
    {"breed": "Affenpinscher"},
    {"breed": "Afghanhund"},
    {"breed": "Africanis"},
    {"breed": "Aidi (Chien de Montagne de l'Atlas)"},
    {"breed": "Ainu, seHokkaido"},
    {"breed": "Airedaleterrier"},
    {"breed": "Akbash"},
    {"breed": "Akita (Akita inu)"},
    {"breed": "Alano español"},
    {"breed": "Alentejomastiff, se Rafeiro do alentejo"},
    {"breed": "Alaskan malamute"},
    {"breed": "Alpenländische dachsbracke"},
    {"breed": "Altdeutsche Hütehunde"},
    {"breed": "American akita (Great japanese dog)"},
    {"breed": "American Bulldog"},
    {"breed": "American English Coonhound"},
    {"breed": "American eskimo dog"},
    {"breed": "American foxhound"},
    {"breed": "American hairless terrier"},
    {"breed": "American Leopard Hound"},
    {"breed": "American staffordshire terrier"},
    {"breed": "American toy fox terrier"},
    {"breed": "American water spaniel (Amerikansk vattenspaniel)"},
    {"breed": "Amerikansk cocker spaniel"},
    {"breed": "Amerikansk pitbullterrier (Pitbull Terrier)"},
    {"breed": "Anatolisk herdehund (Karabash), se Kangal Çoban Köpeği"},
    {"breed": "Anglo-français de petite vénerie"},
    {"breed": "Anglo-russkaja gontjaja (Rysk fläckig stövare)"},
    {"breed": "Appenzeller sennenhund"},
    {"breed": "Ariégeois"},
    {"breed": "Australian cattledog"},
    {"breed": "Australian kelpie"},
    {"breed": "Australian Silky Terrier, se Silky terrier"},
    {"breed": "Australian shepherd"},
    {"breed": "Australian stock dog, se Working kelpie"},
    {"breed": "Australian stumpy tail cattle dog"},
    {"breed": "Australisk terrier"},
    {"breed": "Azawakh"},
    {"breed": "Balgarski barak (Bulgarisk strävhårig stövare)"},
    {"breed": "Balgarsko gontje (Bulgarisk stövare)"},
    {"breed": "Balgarsko ovtjarsko kutje (Karakatjan)"},
    {"breed": "Balkanski gonic, se Serbski gonic"},
    {"breed": "Barbado da Terceira"},
    {"breed": "Barbet (Fransk vattenhund)"},
    {"breed": "Basenji"},
    {"breed": "Basset artésien normand"},
    {"breed": "Basset bleu de gascogne"},
    {"breed": "Basset fauve de bretagne"},
    {"breed": "Basset griffon vendéen; petit och grand"},
    {"breed": "Basset hound"},
    {"breed": "Bayersk viltspårhund"},
    {"breed": "Beagle"},
    {"breed": "Beagle-harrier"},
    {"breed": "Bearded collie"},
    {"breed": "Beauceron (Berger de Bauce)"},
    {"breed": "Bedlingtonterrier"},
    {"breed": "Belgisk vallhund; groenendael, laekenois, malinois och tervueren"},
    {"breed": "Bergamasco"},
    {"breed": "Berger blanc suisse, se Vit herdehund"},
    {"breed": "Berger de Bauce, se Beauceron"},
    {"breed": "Berger de Brie, se Briard"},
    {"breed": "Berger de Crau"},
    {"breed": "Berger des pyrénées (Pyreneisk vallhund); à poil long och à face rase"},
    {"breed": "Berger picard (Picardy)"},
    {"breed": "Berner sennenhund"},
    {"breed": "Bernerstövare, se Schweiziska stövare"},
    {"breed": "Bichon petit chien lion, se Löwchen"},
    {"breed": "Bichon frisé"},
    {"breed": "Bichon havanais (Bichon havanese)"},
    {"breed": "Biewer Terrier"},
    {"breed": "Billy"},
    {"breed": "Black and tan coonhound"},
    {"breed": "Blodhund (Engelsk blodhund)"},
    {"breed": "Blue Lacy"},
    {"breed": "Bluetick coonhound"},
    {"breed": "Boerboel"},
    {"breed": "Bolognese"},
    {"breed": "Bolonka, se Russkaja tsvetnaja bolonka"},
    {"breed": "Border collie"},
    {"breed": "Borderterrier"},
    {"breed": "Borzoi (Rysk vinthund)"},
    {"breed": "Bosanski ostrodlaki gonic-barak"},
    {"breed": "Bostonterrier"},
    {"breed": "Bordeauxdogg, se Dogue de bordeaux"},
    {"breed": "Bouvier des ardennes"},
    {"breed": "Bouvier des flandres"},
    {"breed": "Boxer"},
    {"breed": "Boykin Spaniel"},
    {"breed": "Bracco italiano (Italiensk pointer)"},
    {"breed": "Brandlbracke (vieräugl)"},
    {"breed": "Braque d'auvergne"},
    {"breed": "Braque de l’ariège"},
    {"breed": "Braque du bourbonnais"},
    {"breed": "Braque dupuy (Braque du Puy)"},
    {"breed": "Braque français; type gascogne och type pyrénées"},
    {"breed": "Braque saint-germain"},
    {"breed": "Breton"},
    {"breed": "Briard (Berger de Brie)"},
    {"breed": "Briquet de Provence"},
    {"breed": "Briquet griffon vendéen"},
    {"breed": "Broholmer"},
    {"breed": "Bruno Saint Hubert français"},
    {"breed": "Buldogue campeiro"},
    {"breed": "Buldogue serrano"},
    {"breed": "Bull Dog, se Engelsk bulldogg"},
    {"breed": "Bullenbeisser (utdöd)"},
    {"breed": "Bullmastiff"},
    {"breed": "Bullterrier"},
    {"breed": "Burjat-mongolskij volkodav (Burjatvarghund)"},
    {"breed": "Böhmisk vallhund, se Chodský pes"},
    {"breed": "Ca de bestiar (Perro de pastor mallorquín)"},
    {"breed": "Ca de bou, se Perro dogo mallorquin"},
    {"breed": "Cairnterrier"},
    {"breed": "Canaan dog"},
    {"breed": "Canadian eskimo dog"},
    {"breed": "Cane corso"},
    {"breed": "Cane da pastore Bergamasco, se Bergamasco"},
    {"breed": "Cão da serra da estrela"},
    {"breed": "Cão da serra de aires"},
    {"breed": "Cão de castro laboreiro"},
    {"breed": "Cão de gado transmontano"},
    {"breed": "Cão fila de são miguel"},
    {"breed": "Caravan Hound"},
    {"breed": "Carea leonés (Perro leonés de pastor)"},
    {"breed": "Carolina Dog"},
    {"breed": "Catahoula Leopard Dog"},
    {"breed": "Cavalier king charles spaniel"},
    {"breed": "Cesky fousek"},
    {"breed": "Český horský pes"},
    {"breed": "Český strakatý pes"},
    {"breed": "Ceskyterrier"},
    {"breed": "Ceskoslovenský vlciak (Tjeckoslovakisk varghund)"},
    {"breed": "Chart polski"},
    {"breed": "Chesapeake bay retriever"},
    {"breed": "Chien Corse, se Cursinu"},
    {"breed": "Chien d’artois"},
    {"breed": "Chien de Montagne de l'Atlas, se Aidi"},
    {"breed": "Chien gris de Saint Louis (utdöd)"},
    {"breed": "Chihuahua; kort- och långhårig"},
    {"breed": "Chinese crested dog (Kinesisk nakenhund); hairless och powder puff"},
    {"breed": "Chinook"},
    {"breed": "Chippiparai"},
    {"breed": "Chodský pes (Böhmisk vallhund)"},
    {"breed": "Chortaj"},
    {"breed": "Chow chow"},
    {"breed": "Ciobanesc romanesc carpatin"},
    {"breed": "Ciobanesc romanesc corb"},
    {"breed": "Ciobanesc romanesc de bucovina"},
    {"breed": "Ciobanesc romanesc mioritic"},
    {"breed": "Cimarrón uruguayo"},
    {"breed": "Cirneco dell'etna"},
    {"breed": "Clumber spaniel"},
    {"breed": "Coban Köpegi, se Anatolisk herdehund"},
    {"breed": "Cocker spaniel (Engelsk cocker spaniel)"},
    {"breed": "Collie; kort- och långhårig"},
    {"breed": "Combai (Kombai)"},
    {"breed": "Coton de tuléar"},
    {"breed": "Crnogorski planinski gonic"},
    {"breed": "Curly coated retriever"},
    {"breed": "Cursinu (Chien Corse)"},
    {"breed": "Czeslovakian Wolfdog, se Ceskoslovenský vlciak"},
    {"breed": "Dalbohund (utdöd)"},
    {"breed": "Dalmatiner"},
    {"breed": "Dandie dinmont terrier"},
    {"breed": "Dansk spids"},
    {"breed": "Dansk-svensk gårdshund"},
    {"breed": "Deutsch Drahthaar, se Strävhårig vorsteh"},
    {"breed": "Deutsch Kurzhaar, se Korthårig vorsteh"},
    {"breed": "Deutsch Langhaar, se Långhårig vorsteh"},
    {"breed": "Deutsch stichelhaar (Stichelhaariger deutscher vorsteh)"},
    {"breed": "Deutsche bracke"},
    {"breed": "Deutsche Dogge, se Grand danois"},
    {"breed": "Deutscher Jagdterrier, se Tysk jaktterrier"},
    {"breed": "Deutscher Pinscher, se Pinscher"},
    {"breed": "Dhokhi apso, se Tibetansk terrier"},
    {"breed": "Dingo"},
    {"breed": "Dobermann"},
    {"breed": "Dogo argentino"},
    {"breed": "Dogo canario"},
    {"breed": "Dogo guatemalteco"},
    {"breed": "Dogue brasileiro"},
    {"breed": "Dogue de bordeaux (Bordeauxdogg)"},
    {"breed": "Do-Khyi, se Tibetansk mastiff"},
    {"breed": "Drentsche patrijshond"},
    {"breed": "Drever"},
    {"breed": "Dunkerstövare"},
    {"breed": "Dvärgpinscher"},
    {"breed": "Dvärgpudel, se Pudel"},
    {"breed": "Dvärgschnauzer"},
    {"breed": "Dvärgspets, se Pomeranian"},
    {"breed": "Dvärgtax, se Tax; kort-, lång- och strävhårig"},
    {"breed": "Engelsk blodhund, se Blodhund"},
    {"breed": "Engelsk bulldogg (Bull Dog)"},
    {"breed": "Engelsk cocker spaniel, se Cocker spaniel"},
    {"breed": "Engelsk foxhound, se Foxhound"},
    {"breed": "Engelsk setter"},
    {"breed": "Engelsk springer spaniel"},
    {"breed": "English Coonhound (Redtick Coonhound), se American English Coonhound"},
    {"breed": "English toy terrier"},
    {"breed": "Entlebucher sennenhund"},
    {"breed": "Épagneul Barbet, se Barbet"},
    {"breed": "Épagneul bleu de picardie"},
    {"breed": "Épagneul Breton, se Breton"},
    {"breed": "Épagneul de pont-audemer"},
    {"breed": "Épagneul de saint usuge"},
    {"breed": "Épagneul français"},
    {"breed": "Épagneul picard"},
    {"breed": "Erdélyi kopó"},
    {"breed": "Estnisk stövare (Eesti hagijas)"},
    {"breed": "Eurasier"},
    {"breed": "Euskal Artzain Txakurra, se Perro de Pastor Vasco"},
    {"breed": "Faraohund (Kelbtal Fenek)"},
    {"breed": "Field spaniel"},
    {"breed": "Fila brasileiro"},
    {"breed": "Finsk lapphund (Lapinkoira)"},
    {"breed": "Finsk spets"},
    {"breed": "Finsk stövare"},
    {"breed": "Flat coated retriever"},
    {"breed": "Foxhound"},
    {"breed": "Foxterrier; släthårig och strävhårig"},
    {"breed": "Français blanc et noir"},
    {"breed": "Français blanc et orange"},
    {"breed": "Français tricolore"},
    {"breed": "Fransk bulldogg"},
    {"breed": "Fransk vattenspaniel / Fransk vattenhund, se Barbet"},
    {"breed": "Frisisk vattenhund, se Wetterhoun"},
    {"breed": "Galgo español"},
    {"breed": "Gammel dansk hönsehund"},
    {"breed": "Gampr"},
    {"breed": "Gascon saintongeois, grand och petit"},
    {"breed": "Golden retriever"},
    {"breed": "Gonczy polski"},
    {"breed": "Gordonsetter"},
    {"breed": "Gos d'atura catalá (Perro de pastor catalán, Katalansk vallhund)"},
    {"breed": "Gos Rater Valencià, se Ratonero Valenciano"},
    {"breed": "Gotlandsstövare"},
    {"breed": "Grand anglo-français blanc et noir"},
    {"breed": "Grand anglo-français blanc et orange"},
    {"breed": "Grand anglo-français tricolore"},
    {"breed": "Grand basset griffon vendéen"},
    {"breed": "Grand bleu de gascogne"},
    {"breed": "Grand danois (Deutsche Dogge)"},
    {"breed": "Grand gascon saintongeois, se Gascon saintongeois"},
    {"breed": "Grand griffon vendéen"},
    {"breed": "Great japanese dog, se American akita"},
    {"breed": "Greyhound"},
    {"breed": "Griffon à poil laineux (Griffon Boulet)"},
    {"breed": "Griffon belge"},
    {"breed": "Griffon bleu de gascogne"},
    {"breed": "Griffon bruxellois"},
    {"breed": "Griffon d'arret à poil dur (korthals)"},
    {"breed": "Griffon fauve de bretagne"},
    {"breed": "Griffon nivernais"},
    {"breed": "Groenendael, se Belgisk vallhund"},
    {"breed": "Grosser münsterländer"},
    {"breed": "Grosser schweizer sennenhund"},
    {"breed": "Grosspitz (Tysk spets / Grosspitz)"},
    {"breed": "Gråhund, se Norsk älghund, grå"},
    {"breed": "Grönlandshund"},
    {"breed": "Haldenstövare"},
    {"breed": "Hamiltonstövare"},
    {"breed": "Hannoveransk viltspårhund"},
    {"breed": "Harrier"},
    {"breed": "Hedehund"},
    {"breed": "Hellinikos ichnilatis"},
    {"breed": "Hellinikos poimenikos (Grekisk herdehund)"},
    {"breed": "Hokkaido (Ainu)"},
    {"breed": "Hollandse herdershond (Holländsk vallhund); korthårig, långhårig och strävhårig"},
    {"breed": "Hollandse smoushond"},
    {"breed": "Hovawart"},
    {"breed": "Hrvatski ovcar"},
    {"breed": "Hygenstövare (Hygenhund)"},
    {"breed": "Hälleforshund"},
    {"breed": "Irish glen of imaal terrier"},
    {"breed": "Irish softcoated wheaten terrier"},
    {"breed": "Irländsk röd och vit setter"},
    {"breed": "Irländsk röd setter"},
    {"breed": "Irländsk terrier"},
    {"breed": "Irländsk varghund"},
    {"breed": "Irländsk vattenspaniel"},
    {"breed": "Isländsk fårhund"},
    {"breed": "Istarski gonic (Istrian hound); kratkodlaki och ostrodlaki"},
    {"breed": "Italiensk pointer, se Bracco italiano"},
    {"breed": "Italiensk vinthund"},
    {"breed": "Jack russell terrier"},
    {"breed": "Jakutskaja lajka"},
    {"breed": "Japanese chin"},
    {"breed": "Japansk spets"},
    {"breed": "Japansk terrier, se Nihon teria"},
    {"breed": "Jemtse apso, se Tibetansk spaniel"},
    {"breed": "Jugoslovenski Ovcarski Pas, se Sarplaninac"},
    {"breed": "Jurastövare, se Schweiziska stövare"},
    {"breed": "Juzjnorusskaja ovtjarka (Sydrysk ovtjarka)"},
    {"breed": "Jämthund"},
    {"breed": "Kai (Kai ken)"},
    {"breed": "Kangal Çoban Köpeği (Anatolisk herdehund / Karabash)"},
    {"breed": "Kanintax, se Tax; kort-, lång- och strävhårig"},
    {"breed": "Karabash, se (Karabash)"},
    {"breed": "Karakatjan, se Balgarsko ovtjarsko kutje"},
    {"breed": "Karelsk björnhund"},
    {"breed": "Katalansk vallhund, se Gos d'atura catalá"},
    {"breed": "Kaukasisk ovtjarka, se Kavkazskaja ovtjarka"},
    {"breed": "Kavkazskaja ovtjarka (Kaukasisk ovtjarka)"},
    {"breed": "Keeshond (Tysk spets / Wolfspitz)"},
    {"breed": "Kelpie, se Australian kelpie"},
    {"breed": "Kerry Beagle"},
    {"breed": "Kerry blue terrier"},
    {"breed": "Kinesisk nakenhund, Chinese crested dog"},
    {"breed": "King charles spaniel"},
    {"breed": "Kintamani-Balihund"},
    {"breed": "Kishu"},
    {"breed": "Kleiner münsterländer"},
    {"breed": "Kleinspitz (Tysk spets / Kleinspitz)"},
    {"breed": "Kokoni"},
    {"breed": "Kombai, se Combai"},
    {"breed": "Komondor"},
    {"breed": "Kooikerhondje, se Nederlandse kooikerhondje"},
    {"breed": "Kopó (Transsylvansk kopó), se Erdélyi kopó"},
    {"breed": "Korea jindo dog"},
    {"breed": "Korthals, se Griffon d'arret à poil dur"},
    {"breed": "Korthårig vorsteh (Deutsch Kurzhaar)"},
    {"breed": "Kraski ovcar"},
    {"breed": "Kritikos lagonikos (Kretahund)"},
    {"breed": "Kromfohrländer"},
    {"breed": "Kunming langgou (Kunmingvarghund)"},
    {"breed": "Kuvasz"},
    {"breed": "Labrador retriever"},
    {"breed": "Lagotto romagnolo"},
    {"breed": "Lakelandterrier"},
    {"breed": "Lakenois, se Belgisk vallhund"},
    {"breed": "Lajka, se Rysk-europeisk lajka, Västsibirisk lajka och Östsibirisk"},
    {"breed": "Lancashire heeler"},
    {"breed": "Landseer"},
    {"breed": "Lapphund, se Finsk lapphund och Svensk lapphund"},
    {"breed": "Lapsk vallhund (Lapinporokoira)"},
    {"breed": "Leiko helliniko tsopanoskilo (Vit grekisk herdehund)"},
    {"breed": "Leonberger"},
    {"breed": "Lhasa apso"},
    {"breed": "Lietuviu skalikas (Litauisk stövare)"},
    {"breed": "Lupo italiano"},
    {"breed": "Luzernerstövare, se Schweiziska stövare"},
    {"breed": "Långhårig vorsteh (Deutsch Langhaar)"},
    {"breed": "Löwchen (Bichon petit chien lion)"},
    {"breed": "Magyar agár (Ungersk vinthund)"},
    {"breed": "Majorero"},
    {"breed": "Mali medimurski pas (Medi)"},
    {"breed": "Malinois, se Belgisk vallhund"},
    {"breed": "Mallorcamastiff, se Perro dogo mallorquín"},
    {"breed": "Malteser"},
    {"breed": "Manchesterterrier"},
    {"breed": "Maneto"},
    {"breed": "Maremmano abruzzese (Maremma)"},
    {"breed": "Markiesje"},
    {"breed": "Mastiff"},
    {"breed": "Mastín del Pirineo, se Pyreneisk mastiff"},
    {"breed": "Mastin español (Spansk mastiff)"},
    {"breed": "Mastino napoletano (Neapolitansk mastiff)"},
    {"breed": "Mâtin Belge"},
    {"breed": "Mellanasiatisk ovtjarka, se Sredneasiatskaja ovtjarka"},
    {"breed": "Mellanpinscher, se Pinscher"},
    {"breed": "Mellanpudel, se Pudel"},
    {"breed": "Mellanschnauzer, se Schnauzer"},
    {"breed": "Mexikansk nakenhund, se Xoloitzcuintle"},
    {"breed": "Miniatyrbullterrier"},
    {"breed": "Miniature american shepherd"},
    {"breed": "Mittelspitz (Tysk spets / Mittelspitz)"},
    {"breed": "Molossos tis Ipeiro (Epirusmoloss)"},
    {"breed": "Mops"},
    {"breed": "Moskovskaja storozjevaja (Moskvavakthund)"},
    {"breed": "Moskvadvärgterrier, se Russkiy toy"},
    {"breed": "Mountain Cur"},
    {"breed": "Mudhol, se Caravan Hound"},
    {"breed": "Mudi"},
    {"breed": "Münsterländer; (kleiner münsterländer och grosser münsterländer"},
    {"breed": "Neapolitansk mastiff, se Mastino napoletano"},
    {"breed": "Nederlandse kooikerhondje"},
    {"breed": "Nenetskaja olenegonka lajka, se Olenegonka sjpits"},
    {"breed": "Newfoundlandshund"},
    {"breed": "Nihon teria (Japansk terrier)"},
    {"breed": "Norfolkterrier"},
    {"breed": "Norrbottenspets"},
    {"breed": "Norsk buhund"},
    {"breed": "Norsk lundehund"},
    {"breed": "Norsk älghund, grå (Gråhund)"},
    {"breed": "Norsk älghund, svart"},
    {"breed": "Norwichterrier"},
    {"breed": "Nova scotia duck tolling retriever"},
    {"breed": "Nya Guineas sjungande hund"},
    {"breed": "Olde english bulldogge brasileiro"},
    {"breed": "Ogar polski"},
    {"breed": "Ohar, se Slovenský hrubosrsty stavac"},
    {"breed": "Old english sheepdog"},
    {"breed": "Olenegonnyj sjpits (Nenetskaja olenegonka lajka, Nenetsrenhund)"},
    {"breed": "Otterhound (Utterhund)"},
    {"breed": "Ovejero magallánico"},
    {"breed": "Ovelheiro gaúcho"},
    {"breed": "Pachón navarro"},
    {"breed": "Papillon"},
    {"breed": "Parson russell terrier"},
    {"breed": "Pashmi, se Caravan Hound"},
    {"breed": "Pekingese"},
    {"breed": "Perdiguero de burgos"},
    {"breed": "Perdigueiro português"},
    {"breed": "Perro de agua español (Spansk vattenhund)"},
    {"breed": "Perro de pastor catalán, se Gos d'atura catalá"},
    {"breed": "Perro de pastor garafiano"},
    {"breed": "Perro de pastor mallorquín, se Ca de bestiar"},
    {"breed": "Perro de pastor vasco (Euskal Artzain Txakurra)"},
    {"breed": "Perro dogo mallorquín (Ca de bou, Mallorcamastiff)"},
    {"breed": "Perro leonés de pastor, se Carea leonés"},
    {"breed": "Perro sin pelo del perú (Peruansk nakenhund); liten, mellan och stor"},
    {"breed": "Peruansk nakenhund, se Perro sin pelo de perú"},
    {"breed": "Petit basset griffon vendéen"},
    {"breed": "Petit bleu de gascogne"},
    {"breed": "Petit gascon saintongeois, se Gascon saintongeois"},
    {"breed": "Petit brabancon"},
    {"breed": "Phaléne"},
    {"breed": "Picardy, se Berger picard"},
    {"breed": "Pinscher"},
    {"breed": "Pitbull Terrier (se Amerikansk pitbullterrier)"},
    {"breed": "Plott"},
    {"breed": "Podenco andaluz"},
    {"breed": "Podenco canario"},
    {"breed": "Podenco ibicenco, korthårig och strävhårig"},
    {"breed": "Podenco valenciano"},
    {"breed": "Podengo portugues, cerdoso och liso"},
    {"breed": "Pointer"},
    {"breed": "Poitevin"},
    {"breed": "Polski owczarek nizinny"},
    {"breed": "Polski owczarek podhalanski"},
    {"breed": "Pomeranian (Tysk spets / Zwergspitz, Dvärgspets)"},
    {"breed": "Porcelaine"},
    {"breed": "Portugisisk vattenhund (Cão de agua portugués)"},
    {"breed": "Posavski gonic"},
    {"breed": "Prazský krysarík"},
    {"breed": "Pudel"},
    {"breed": "Pudelpointer"},
    {"breed": "Puli"},
    {"breed": "Pumi"},
    {"breed": "Pyrenéerhund"},
    {"breed": "Pyreneisk mastiff"},
    {"breed": "Pyreneisk vallhund, se Berger des pyrénées"},
    {"breed": "Rafeiro do alentejo (Alentejomastiff)"},
    {"breed": "Rajapalayam"},
    {"breed": "Rampur Hound"},
    {"breed": "Rastreador brasileiro"},
    {"breed": "Ratonero bodeguero andaluz"},
    {"breed": "Ratonero valenciano (Gos rater valencià)"},
    {"breed": "Rat terrier"},
    {"breed": "Redbone Coonhound"},
    {"breed": "Redtick Coonhound, se American English Coonhound"},
    {"breed": "Rhodesian ridgeback"},
    {"breed": "Riesenschnauzer"},
    {"breed": "Rottweiler"},
    {"breed": "Russkaja gontjaja (Rysk stövare)"},
    {"breed": "Russkaja ochotnitjija spaniel (Rysk jaktspaniel)"},
    {"breed": "Russkaja pegaja gontjaja, se Anglo-russkaja gontjaja"},
    {"breed": "Russkaja tsvetnaja bolonka"},
    {"breed": "Russkiy toy (Moskvadvärgterrier)"},
    {"breed": "Rysk-europeisk lajka"},
    {"breed": "Rysk fläckig stövare, se Anglo-russkaja gontjaja"},
    {"breed": "Rysk stövare, se Russkaja gontjaja"},
    {"breed": "Rysk svart terrier (Tjornyj terjer)"},
    {"breed": "Rysk vinthund, se Borzoi"},
    {"breed": "Saarloos wolfhond"},
    {"breed": "Sabueso español"},
    {"breed": "Saluki"},
    {"breed": "Samojedhund"},
    {"breed": "St. John's Dog (utdöd)"},
    {"breed": "Sankt bernhardshund; kort- och långhårig"},
    {"breed": "Sarplaninac (Jugoslovenski ovcarski pas)"},
    {"breed": "Schafpudel"},
    {"breed": "Schapendoes"},
    {"breed": "Schillerstövare"},
    {"breed": "Schipperke"},
    {"breed": "Schnauzer (Mellanschnauzer)"},
    {"breed": "Schweizer sennenhund, se Grosser schweizer sennenhund"},
    {"breed": "Schweiziska små stövare; berner, jura, luzerner och schwyzer"},
    {"breed": "Schweiziska stövare; berner, jura, luzerner och schwyzer"},
    {"breed": "Schwyzerstövare, se Schweiziska stövare"},
    {"breed": "Schäfer, se Tysk schäferhund"},
    {"breed": "Sealyhamterrier"},
    {"breed": "Segugio dell'Appennino"},
    {"breed": "Segugio italiano, korthårig eller strävhårig"},
    {"breed": "Segugio maremmano, korthårig eller strävhårig"},
    {"breed": "Serbski gonic (Balkanski gonic)"},
    {"breed": "Serbski trobojni gonic"},
    {"breed": "Shar pei"},
    {"breed": "Shetland sheepdog"},
    {"breed": "Shiba"},
    {"breed": "Shih tzu"},
    {"breed": "Shikoku"},
    {"breed": "Siberian husky"},
    {"breed": "Silken Windhound"},
    {"breed": "Silkyterrier (Australian Silky Terrier)"},
    {"breed": "Skotsk hjorthund"},
    {"breed": "Skotsk terrier"},
    {"breed": "Skyeterrier"},
    {"breed": "Sloughi"},
    {"breed": "Slovenský cuvac"},
    {"breed": "Slovenský hrubosrsty stavac (Ohar)"},
    {"breed": "Slovenský kopov"},
    {"breed": "Släthårig foxterrier"},
    {"breed": "Smålandsstövare"},
    {"breed": "Spansk mastiff, se Mastin español"},
    {"breed": "Spansk vattenhund, se Perro de agua español"},
    {"breed": "Spinone"},
    {"breed": "Sredneasiatskaja ovtjarka (Mellanasiatisk ovtjarka)"},
    {"breed": "Srpski pastirski pas (Serbisk herdehund)"},
    {"breed": "Stabijhoun"},
    {"breed": "Staffordshire bullterrier"},
    {"breed": "Steirische rauhhaarbracke"},
    {"breed": "Stichelhaariger deutscher vorsteh, se Deutsch stichelhaar"},
    {"breed": "Storpudel, se Pudel"},
    {"breed": "Strellufstövare, se Drever"},
    {"breed": "Strävhårig foxterrier"},
    {"breed": "Strävhårig vorsteh (Deutsch Drahthaar)"},
    {"breed": "Sulimovhund"},
    {"breed": "Sussex spaniel"},
    {"breed": "Svart terrier, se Rysk svart terrier"},
    {"breed": "Svensk lapphund"},
    {"breed": "Svensk vit älghund"},
    {"breed": "Sydrysk ovtjarka, se Juzjnorusskaja ovtjarka"},
    {"breed": "Taigan[1]"},
    {"breed": "Taiwan dog"},
    {"breed": "Tax; kort-, lång- och strävhårig"},
    {"breed": "Teddy Roosevelt Terrier"},
    {"breed": "Tenterfield terrier"},
    {"breed": "Terrier brasileiro"},
    {"breed": "Terrier chileno"},
    {"breed": "Tervueren, se Belgisk vallhund"},
    {"breed": "Thai bangkaew dog"},
    {"breed": "Thai ridgeback dog"},
    {"breed": "Tibetansk mastiff (Do-Khyi)"},
    {"breed": "Tibetansk spaniel"},
    {"breed": "Tibetansk terrier (Dhokhi apso)"},
    {"breed": "Tirolerbracke"},
    {"breed": "Tjornyj terjer, se Svart terrier"},
    {"breed": "Tjukotskaja jesdovaja"},
    {"breed": "Tornjak"},
    {"breed": "Tosa (Tosa inu)"},
    {"breed": "Toy Fox Terrier, se American toy fox terrier"},
    {"breed": "Toypudel, se Pudel"},
    {"breed": "Transsylvansk kopó, se Erdélyi kopó"},
    {"breed": "Treeing Tennessee Brindle"},
    {"breed": "Treeing walker coonhound"},
    {"breed": "Tweed Water Spaniel (utdöd)"},
    {"breed": "Tysk jaktterrier (Deutscher Jagdterrier)"},
    {"breed": "Tysk schäferhund; normalhårig och långhårig"},
    {"breed": "Tysk spets; grosspitz, kleinspitz, mittelspitz, keeshond (wolfspitz) och pomeranian (zwergspitz / dvärgspets)"},
    {"breed": "Ungersk vinthund, se Magyar agár"},
    {"breed": "Ungersk viszla, kort- och strävhårig"},
    {"breed": "Utterhund, se Otterhound"},
    {"breed": "Veadeiro pampeano"},
    {"breed": "Vit herdehund (Berger blanc suisse)"},
    {"breed": "Volpino italiano"},
    {"breed": "Vorsteh; kort- (Deutsch Kurzhaar), lång- (Deutsch Langhaar) och strävhårig (Deutsch Drahthaar)"},
    {"breed": "Vostotjnoevropejskaja ovtjarka (Östeuropeisk ovtjarka)"},
    {"breed": "Västgötaspets"},
    {"breed": "Västsibirisk lajka"},
    {"breed": "Wachtelhund"},
    {"breed": "Weimaraner"},
    {"breed": "Welsh corgi cardigan"},
    {"breed": "Welsh corgi pembroke"},
    {"breed": "Welsh springer spaniel"},
    {"breed": "Welshterrier"},
    {"breed": "West highland white terrier"},
    {"breed": "Westfälische dachsbracke"},
    {"breed": "Wetterhoun (Frisisk vattenhund)"},
    {"breed": "Whippet"},
    {"breed": "Viszla, se Ungersk vizsla"},
    {"breed": "Wolfspitz, se Keeshond"},
    {"breed": "Working kelpie"},
    {"breed": "Xoloitzcuintle (Mexikansk nakenhund); liten, mellan och stor"},
    {"breed": "Yorkshireterrier"},
    {"breed": "Zwergspitz, se Pomeranian"},
    {"breed": "Österreichischer pinscher (Österreichischer kurzhaariger pinscher)"},
    {"breed": "Östsibirisk lajka"},
]


