# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Kontorshund to Docker Hub

on:
 push:
   branches:
     - master

jobs:

 # test:
 # runs-on: ubuntu-latest

 # steps:

 # - uses: actions/checkout@v2

 # - name: Install dependencies
 # run: |
 # python3 -m pip install --upgrade pip
 # pip3 install -r requirements.txt

 # - name: run test bequoted backend

 # run: python3 projectile/manage.py test cmd common core distribution mail nasdaq publication socialize taskmanagement

 build:
   runs-on: 'ubuntu-latest'

   steps:
   - uses: actions/checkout@v2

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1

   - name: Log in to Docker Hub
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       #password: ${{ secrets.DOCKER_HUB_TOKEN }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}

   - name: Build and push container image to registry
     uses: docker/build-push-action@v2
     with:
       push: true
       tags: oneandonly1337/kontorshund:latest
       file: ./Dockerfile.prod
